=== ReemShkeep/ITI-XML/lab1/lab1-library.dtd
<!ELEMENT Library (Location, Description, Librarian, Books)>
<!ELEMENT Location (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Librarian (#PCDATA)>
<!ELEMENT Books (Book+) >
<!ELEMENT Book (ISBN, BookName, Author,Parts)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT BookName (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Parts (Part+)>
<!ELEMENT Part (PartName,Chapters)*>
<!ELEMENT PartName (#PCDATA)>
<!ELEMENT Chapters (Chapter+)>
<!ELEMENT Chapter (Title,Summary,Sections+)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Summary (#PCDATA)>
<!ELEMENT Sections (Section+)>
<!ELEMENT Section (#PCDATA)>

=== ReemShkeep/ITI-XML/lab1/lab1-library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Library SYSTEM "lab1-library.dtd">

<Library>
   <Location>Library Location</Location>
   <Description>Library Description</Description>
   <Librarian>Library Librarian</Librarian>
   <Books>

      <Book>
         <ISBN>Book Id</ISBN>
         <BookName>Book Name</BookName>
         <Author>Book Author</Author>
         <Parts>
            <Part>
               <PartName>Part Name</PartName>
               <Chapters>
                  <Chapter>
                     <Title>Chapter Title</Title>
                     <Summary>Chapter Summary</Summary>
                     <Sections>
                        <Section>Chapter Section 1</Section>
                        <Section>Chapter Section 2</Section>
                     </Sections>
                  </Chapter>
                  <Chapter>
                     <Title>Chapter Title</Title>
                     <Summary>Chapter Summary</Summary>
                     <Sections>
                        <Section>Chapter Section 1</Section>
                        <Section>Chapter Section 2</Section>
                     </Sections>
                  </Chapter>
               </Chapters>
            </Part>
         </Parts>
      </Book>

      <Book>
         <ISBN>Book Id</ISBN>
         <BookName>Book Name</BookName>
         <Author>Book Author</Author>
         <Parts>
            <Part>
               <PartName>Part Name</PartName>
               <Chapters>
                  <Chapter>
                     <Title>Chapter Title</Title>
                     <Summary>Chapter Summary</Summary>
                     <Sections>
                        <Section>Chapter Section 1</Section>
                        <Section>Chapter Section 2</Section>
                     </Sections>
                  </Chapter>
                  <Chapter>
                     <Title>Chapter Title</Title>
                     <Summary>Chapter Summary</Summary>
                     <Sections>
                        <Section>Chapter Section 1</Section>
                        <Section>Chapter Section 2</Section>
                     </Sections>
                  </Chapter>
               </Chapters>
            </Part>
         </Parts>
      </Book>

      <Book>
         <ISBN>Book Id</ISBN>
         <BookName>Book Name</BookName>
         <Author>Book Author</Author>
         <Parts>
            <Part>
               <PartName>Part Name</PartName>
               <Chapters>
                  <Chapter>
                     <Title>Chapter Title</Title>
                     <Summary>Chapter Summary</Summary>
                     <Sections>
                        <Section>Chapter Section 1</Section>
                        <Section>Chapter Section 2</Section>
                     </Sections>
                  </Chapter>
                  <Chapter>
                     <Title>Chapter Title</Title>
                     <Summary>Chapter Summary</Summary>
                     <Sections>
                        <Section>Chapter Section 1</Section>
                        <Section>Chapter Section 2</Section>
                     </Sections>
                  </Chapter>
               </Chapters>
            </Part>
         </Parts>
      </Book>

   </Books>
</Library>
